# ==============================================================
# app.py  → Landing page for Intrusion Detection Project
# ==============================================================
# This file will:
#   - Set Streamlit page configuration (title, icon, layout)
#   - Display project title and introduction
#   - Explain objectives (ML + Automata + Fullstack + Network)
#   - Describe CICIDS2017 dataset (summary only)
#   - Guide users to use other pages in /pages/ folder
#
# NOTE: Streamlit automatically detects files in /pages/ and
#       shows them as tabs in the sidebar (multi-page app).
# ==============================================================

import streamlit as st

# --------------------------------------------------------------
# PAGE CONFIGURATION
# --------------------------------------------------------------
st.set_page_config(
    page_title="Intrusion Detection (CICIDS2017)",
    page_icon="🚨",
    layout="wide"
)

# --------------------------------------------------------------
# HEADER SECTION
# --------------------------------------------------------------
st.title("🚨 Intrusion Detection using ML & Automata")
st.markdown("""
**Core Project**: *Fullstack + Machine Learning + Automata + Network Integration*
""")

# --------------------------------------------------------------
# PROJECT EXPLANATION
# --------------------------------------------------------------
with st.expander("📘 Project Explanation", expanded=True):
    st.write("""
    Intrusion Detection Systems (IDS) are the first line of defense 
    against malicious activities in a network. 

    In this project:
    - We train a **Deep Learning model** on the **CICIDS2017 dataset**.
    - We design a **rule-based Automata IDS** (baseline).
    - We compare both approaches in terms of accuracy, precision, recall, and F1-score.
    - We build an **interactive Streamlit dashboard** to visualize results.

    The integration covers:
    - **Machine Learning** → Train/test model on dataset
    - **Automata Theory** → Rule-based detection (regex/state machines)
    - **Fullstack** → Streamlit multipage dashboard
    - **Networking** → Simulation of IDS/IPS pipeline
    """)

# --------------------------------------------------------------
# DATASET DESCRIPTION (BRIEF)
# --------------------------------------------------------------
with st.expander("📂 Dataset: CICIDS2017", expanded=False):
    st.write("""
    The **CICIDS2017 dataset** contains realistic benign and malicious traffic 
    captured over **5 days (July 3–7, 2017)**. 

    It includes:
    - Benign user activities (HTTP, HTTPS, FTP, SSH, Email, etc.)
    - Attacks such as:
      - Brute Force FTP/SSH  
      - DoS & DDoS  
      - Heartbleed  
      - Web Attack  
      - Infiltration  
      - Botnet  

    **Key Features:**
    - >80 network flow features per record  
    - Labeled dataset (Benign vs Attack classes)  
    - Mix of protocols & heterogeneous traffic  
    - Size: ~60GB (CSV + PCAPs)  

    We use **CSV flow-based data** generated by CICFlowMeter for training.
    """)

# --------------------------------------------------------------
# NAVIGATION GUIDE
# --------------------------------------------------------------
st.markdown("---")
st.subheader("📑 How to use this Dashboard")
st.markdown("""
Navigate using the sidebar →  

1. **Dataset Explorer** → Preview CICIDS2017 samples  
2. **Preprocessing** → Feature selection & normalization  
3. **ML Model** → Train/Evaluate deep learning classifier  
4. **Automata Baseline** → Rule-based IDS evaluation  
5. **Comparison** → Metrics side-by-side (ML vs Automata)  
6. **Prediction Demo** → Try custom inputs & see IDS output  
7. **Network Simulation** → Simulate real-time packet feed  
""")

# --------------------------------------------------------------
# FOOTER
# --------------------------------------------------------------
st.markdown("---")
st.info("Developed as Core Project: Intrusion Detection with ML, Automata, Networking, and Fullstack Integration")
